version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "
      uvicorn main:app
      --host 0.0.0.0 --port 80
      --reload
      "
    volumes:
      - .:/www
    ports:
      - "80:80"

  mysql:
    image: mysql:5.7
    env_file:
      - .env

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - "3306:3306"    

volumes:
  mysql_data:     
    